### ISSUE TITLE
upload authentication bug

### ISSUE THREAD

**Issue by hredestig** [DD-DeCaF/upload#16]
All attempts at upload now (for me at least) yields

```
[web-1]2017-04-10T08:44:28.280219548Z [2017-04-10 08:44:28 +0000] [11] [ERROR] Error handling request
[web-1]2017-04-10T08:44:28.280259070Z Traceback (most recent call last):
[web-1]2017-04-10T08:44:28.280266355Z   File "/usr/local/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 417, in start
[web-1]2017-04-10T08:44:28.280292355Z     resp = yield from self._request_handler(request)
[web-1]2017-04-10T08:44:28.280299263Z   File "/usr/local/lib/python3.5/site-packages/aiohttp/web.py", line 289, in _handle
[web-1]2017-04-10T08:44:28.280303936Z     resp = yield from handler(request)
[web-1]2017-04-10T08:44:28.280308050Z   File "/upload/upload/app.py", line 30, in wrapper
[web-1]2017-04-10T08:44:28.280312331Z     return await f(request, iloop)
[web-1]2017-04-10T08:44:28.280316431Z   File "/upload/upload/app.py", line 72, in upload
[web-1]2017-04-10T08:44:28.280320785Z     data = await request.post()
[web-1]2017-04-10T08:44:28.280326051Z   File "/usr/local/lib/python3.5/site-packages/aiohttp/web_request.py", line 412, in post
[web-1]2017-04-10T08:44:28.280332791Z     if content_type.startswith('text/'):
[web-1]2017-04-10T08:44:28.280339598Z AttributeError: 'NoneType' object has no attribute 'startswith'
```

Something going awry with in the `call_iloop_with_token` but can't reproduce locally @sgalkina any idea?

**Comment by sgalkina** [comment]
looks like ongoing issue in aiohttp v2.0.0 https://github.com/aio-libs/aiohttp/pull/1748
on our side we need to have aiohttp version set to 1.3.5 like in model service https://github.com/DD-DeCaF/model/blob/master/requirements.txt#L1
